name: metareward
description: Metareward is a node reward distribution script.
version: 1.0.0
# homepage: https:/mhc.watch

environment:
  sdk: '>=2.16.0-134.0.dev <3.0.0'


dependencies:
  hex: ^0.2.0
  pointycastle: ^3.4.0
  asn1lib: ^1.0.3
  http: ^0.13.4
  yaml: ^3.1.0
  cron: ^0.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
